spring:
  application:
    name: greeting-service

server:
  port: 8080

ribbon:
  eureka:
    enabled: false
  client:
    enabled: true
    # We will use Spring Cloud Kubernetes Ribbon to retrieve the list of the servers
    # listOfServers: backend:8080
    ServerListRefreshInterval: 15000

hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 3
      metrics:
        healthSnapshot:
          intervalInMilliseconds: 100
